blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/USERNAME/REPOSITORY/tree/main/docs
    about: Check the documentation for common questions
  - name: Discussions
    url: https://github.com/USERNAME/REPOSITORY/discussions
    about: Ask questions and discuss ideas with the community