"""Add GDPR compliance features

Revision ID: b50062a5f253
Revises: ec05bd5d3888
Create Date: 2025-09-19 14:26:29.192058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50062a5f253'
down_revision = 'ec05bd5d3888'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('consents_granted', sa.Integer(), nullable=True),
    sa.Column('consents_withdrawn', sa.Integer(), nullable=True),
    sa.Column('data_exports_requested', sa.Integer(), nullable=True),
    sa.Column('data_deletions_requested', sa.Integer(), nullable=True),
    sa.Column('data_breaches_detected', sa.Integer(), nullable=True),
    sa.Column('compliance_violations', sa.Integer(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('issues_identified', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_compliance_report_period', 'compliance_reports', ['period_start', 'period_end'], unique=False)
    op.create_index('idx_compliance_report_type', 'compliance_reports', ['report_type', 'status'], unique=False)
    op.create_index(op.f('ix_compliance_reports_report_id'), 'compliance_reports', ['report_id'], unique=True)
    op.create_table('data_retention_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('policy', sa.Enum('PERSONAL_DATA', 'CONVERSATION_DATA', 'ANALYTICS_DATA', 'AUDIT_DATA', 'CONSENT_RECORDS', name='dataretentionpolicy'), nullable=False),
    sa.Column('scheduled_deletion_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processing_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_successful', sa.Boolean(), nullable=True),
    sa.Column('deletion_error', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('legal_basis', sa.String(length=100), nullable=True),
    sa.Column('retention_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retention_entity', 'data_retention_schedules', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_retention_policy', 'data_retention_schedules', ['policy'], unique=False)
    op.create_index('idx_retention_scheduled', 'data_retention_schedules', ['scheduled_deletion_at', 'processed'], unique=False)
    op.create_index(op.f('ix_data_retention_schedules_schedule_id'), 'data_retention_schedules', ['schedule_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'CONSENT_GRANTED', 'CONSENT_WITHDRAWN', 'DATA_EXPORTED', 'DATA_DELETED', 'FRAUD_DETECTED', 'COMPLIANCE_VIOLATION', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('user_identifier', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('compliance_relevant', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_entity', 'audit_logs', ['action', 'entity_type'], unique=False)
    op.create_index('idx_audit_buyer_created', 'audit_logs', ['buyer_id', 'created_at'], unique=False)
    op.create_index('idx_audit_compliance_risk', 'audit_logs', ['compliance_relevant', 'risk_level'], unique=False)
    op.create_index('idx_audit_created_desc', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_audit_logs_audit_id'), 'audit_logs', ['audit_id'], unique=True)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.Enum('DATA_PROCESSING', 'AUTOMATED_COMMUNICATION', 'CONVERSATION_LOGGING', 'ANALYTICS_COLLECTION', 'MARKETING_COMMUNICATION', name='consenttype'), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'WITHDRAWN', 'EXPIRED', 'PENDING', name='consentstatus'), nullable=False),
    sa.Column('legal_basis', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('consent_version', sa.String(length=20), nullable=True),
    sa.Column('consent_evidence', sa.JSON(), nullable=True),
    sa.Column('withdrawal_evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_buyer_type', 'consent_records', ['buyer_id', 'consent_type'], unique=False)
    op.create_index('idx_consent_granted_withdrawn', 'consent_records', ['granted_at', 'withdrawn_at'], unique=False)
    op.create_index('idx_consent_status_expires', 'consent_records', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_consent_records_consent_id'), 'consent_records', ['consent_id'], unique=True)
    op.add_column('buyers', sa.Column('gdpr_consent_given', sa.Boolean(), nullable=True))
    op.add_column('buyers', sa.Column('gdpr_consent_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buyers', sa.Column('data_processing_consent', sa.Boolean(), nullable=True))
    op.add_column('buyers', sa.Column('marketing_consent', sa.Boolean(), nullable=True))
    op.add_column('buyers', sa.Column('anonymized', sa.Boolean(), nullable=True))
    op.add_column('buyers', sa.Column('pseudonymized', sa.Boolean(), nullable=True))
    op.add_column('buyers', sa.Column('deletion_requested', sa.Boolean(), nullable=True))
    op.add_column('buyers', sa.Column('deletion_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('buyers', sa.Column('data_export_requested', sa.Boolean(), nullable=True))
    op.create_index('idx_buyer_deletion', 'buyers', ['deletion_requested', 'deletion_scheduled_at'], unique=False)
    op.create_index('idx_buyer_gdpr_consent', 'buyers', ['gdpr_consent_given', 'gdpr_consent_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buyer_gdpr_consent', table_name='buyers')
    op.drop_index('idx_buyer_deletion', table_name='buyers')
    op.drop_column('buyers', 'data_export_requested')
    op.drop_column('buyers', 'deletion_scheduled_at')
    op.drop_column('buyers', 'deletion_requested')
    op.drop_column('buyers', 'pseudonymized')
    op.drop_column('buyers', 'anonymized')
    op.drop_column('buyers', 'marketing_consent')
    op.drop_column('buyers', 'data_processing_consent')
    op.drop_column('buyers', 'gdpr_consent_date')
    op.drop_column('buyers', 'gdpr_consent_given')
    op.drop_index(op.f('ix_consent_records_consent_id'), table_name='consent_records')
    op.drop_index('idx_consent_status_expires', table_name='consent_records')
    op.drop_index('idx_consent_granted_withdrawn', table_name='consent_records')
    op.drop_index('idx_consent_buyer_type', table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_audit_logs_audit_id'), table_name='audit_logs')
    op.drop_index('idx_audit_created_desc', table_name='audit_logs')
    op.drop_index('idx_audit_compliance_risk', table_name='audit_logs')
    op.drop_index('idx_audit_buyer_created', table_name='audit_logs')
    op.drop_index('idx_audit_action_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_data_retention_schedules_schedule_id'), table_name='data_retention_schedules')
    op.drop_index('idx_retention_scheduled', table_name='data_retention_schedules')
    op.drop_index('idx_retention_policy', table_name='data_retention_schedules')
    op.drop_index('idx_retention_entity', table_name='data_retention_schedules')
    op.drop_table('data_retention_schedules')
    op.drop_index(op.f('ix_compliance_reports_report_id'), table_name='compliance_reports')
    op.drop_index('idx_compliance_report_type', table_name='compliance_reports')
    op.drop_index('idx_compliance_report_period', table_name='compliance_reports')
    op.drop_table('compliance_reports')
    # ### end Alembic commands ###