"""Initial schema creation

Revision ID: ec05bd5d3888
Revises: 
Create Date: 2025-09-19 14:18:09.558655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec05bd5d3888'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('active_conversations_count', sa.Integer(), nullable=True),
    sa.Column('messages_sent_today', sa.Integer(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_rate_limited', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_sessions_session_id'), 'bot_sessions', ['session_id'], unique=True)
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallapop_user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('completed_purchases', sa.Integer(), nullable=True),
    sa.Column('cancelled_conversations', sa.Integer(), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buyer_active', 'buyers', ['is_blocked', 'last_active_at'], unique=False)
    op.create_index(op.f('ix_buyers_wallapop_user_id'), 'buyers', ['wallapop_user_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallapop_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'INACTIVE', name='productstatus'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('favorites_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_price', 'products', ['price'], unique=False)
    op.create_index('idx_product_status_created', 'products', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_products_wallapop_id'), 'products', ['wallapop_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallapop_chat_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'BLOCKED', name='conversationstatus'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('negotiated_price', sa.Float(), nullable=True),
    sa.Column('meeting_location', sa.String(length=200), nullable=True),
    sa.Column('meeting_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intent_detected', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('bot_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'buyer_id', name='uq_product_buyer')
    )
    op.create_index('idx_conversation_product_buyer', 'conversations', ['product_id', 'buyer_id'], unique=False)
    op.create_index('idx_conversation_status_updated', 'conversations', ['status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_wallapop_chat_id'), 'conversations', ['wallapop_chat_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallapop_message_id', sa.String(length=50), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('USER_MESSAGE', 'BOT_MESSAGE', 'SYSTEM_MESSAGE', name='messagetype'), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_message_type_processed', 'messages', ['message_type', 'is_processed'], unique=False)
    op.create_index(op.f('ix_messages_wallapop_message_id'), 'messages', ['wallapop_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_wallapop_message_id'), table_name='messages')
    op.drop_index('idx_message_type_processed', table_name='messages')
    op.drop_index('idx_message_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_wallapop_chat_id'), table_name='conversations')
    op.drop_index('idx_conversation_status_updated', table_name='conversations')
    op.drop_index('idx_conversation_product_buyer', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_products_wallapop_id'), table_name='products')
    op.drop_index('idx_product_status_created', table_name='products')
    op.drop_index('idx_product_price', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_buyers_wallapop_user_id'), table_name='buyers')
    op.drop_index('idx_buyer_active', table_name='buyers')
    op.drop_table('buyers')
    op.drop_index(op.f('ix_bot_sessions_session_id'), table_name='bot_sessions')
    op.drop_table('bot_sessions')
    # ### end Alembic commands ###